version: 3
meta:
  standard-conditions: &standard-conditions
    - >
      contains_any_fnmatches(files, [
        ".github/workflows/*",
        ".pullapprove.yml",
        "tox.ini",
        "CODE_OF_CONDUCT.md",
        ])
pullapprove_conditions: *standard-conditions
groups:
  roadies:
    conditions: *standard-conditions
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
    labels:
      pending: "roadies"
notifications:
- when: pullapprove.group.requested_reviewers
  comment: |
    {{ event.group }} review requested from {{ text_list(event.requested_reviewers.mentions, "and") }}
