version: 3
groups:
  sensitive-files:
    conditions:
    - "'tox.ini' in files or '.pullapprove.yml' in files or '.github/workflows/*' in files or 'CODE_OF_CONDUCT.md' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
