version: 3
pullapprove_conditions:
- >
  contains_any_fnmatches(files, [
    ".github/workflows/*",
    ".pullapprove.yml",
    "tox.ini",
    "CODE_OF_CONDUCT.md",
    ])
groups:
  roadies:
    conditions:
    - >
      contains_any_fnmatches(files, [
        ".github/workflows/*",
        ".pullapprove.yml",
        "tox.ini",
        "CODE_OF_CONDUCT.md",
        ])
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
    labels:
      pending: "roadies"
