version: 3

groups:
  github-workflows:
    conditions:
    - "'.github/workflows/*' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1

  pullapprove-config:
    conditions:
    - "'.pullapprove.yml' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1

  tox-ini:
    conditions:
    - "'tox.ini' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
