version: 3
groups:
  roadies:
    conditions:
    - >
      contains_any_fnmatches(files, [
        ".github/workflows/*",
        ".pullapprove.yml",
        "tox.ini",
        "CODE_OF_CONDUCT.md",
        ])
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
notifications:
- when: pullapprove.group.requested_reviewers
  comment: |
    {{ event.group }} review requested from {{ text_list(event.requested_reviewers.mentions, "and") }}
