version: 3

groups:
  github-workflows:
    conditions:
    - "'.github/workflows/*' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
    labels:
      pending: "roadies"

  pullapprove-config:
    conditions:
    - "'.pullapprove.yml' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
    labels:
      pending: "roadies"

  tox-ini:
    conditions:
    - "'tox.ini' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
    labels:
      pending: "roadies"

  code-of-conduct:
    conditions:
    - "'CODE_OF_CONDUCT.md' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
    labels:
      pending: "roadies"

notifications:
- when: pullapprove.group.requested_reviewers
  comment: |
    {{ event.group }} review requested from {{ text_list(event.requested_reviewers.mentions, "and") }}
