version: 3
groups:
  roadies:
    conditions:
    - "'tox.ini' in files or '.pullapprove.yml' in files or '.github/workflows/*' in files or 'CODE_OF_CONDUCT.md' in files"
    reviewers:
      teams:
      - roadies
    reviews:
      required: 1
    labels:
      pending: "roadies"
notifications:
- when: pullapprove.group.requested_reviewers
  comment: |
    {{ event.group }} review requested from {{ text_list(event.requested_reviewers.mentions, "and") }}
